### PR TITLE
fix truncate err handling

### PR DESCRIPTION
**Pull request by vadiminshakov**

### CODE REVIEW

**Comment by vadimInshakov** [comment]
@tidwall please look at this pr

**Comment by vadiminshakov** [comment]
Issue: https://github.com/tidwall/wal/issues/26

**Comment by tidwall** [comment]
I'm a little slow the other labors atm so I haven't had a chance to do a full review yet, but it looks fine on the surface.
Stay tuned.

**Comment by rockwotj** [comment]
@tidwall any chance you have a moment to look at this?

**Comment by tidwall** [comment]
sorry for the slowness. 😅 lgtm

**Pull request merged**
